name: baidupan
description: For wrapper baidu netdisk api with dart, user can use the package to query, update ,upload or download for baidu netdisk.
version: 1.0.4
homepage: https://github.com/Caijinglong/baidupan
publish_to: https://pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  http: ^0.13.3
  crypto: ^3.0.1

executables:
  bd_upload:
  requset_baidu_auth:
